version: '3.8'

x-node-variables: &node-variables
  NODE_ENV: development

services:
  users:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ./node_modules/.bin/nx serve users
    environment: *node-variables
    ports:
      - 3001:3000
      - 9230:9229
    depends_on:
      - redis
      - db

  reservations:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ./node_modules/.bin/nx serve reservations
    environment: *node-variables
    ports:
      - 3002:3000
      - 9231:9229
    depends_on:
      - redis
      - db

  availability:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ./node_modules/.bin/nx serve availability
    environment: *node-variables
    ports:
      - 3003:3000
      - 9232:9229
    depends_on:
      - redis
      - db

  books:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ./node_modules/.bin/nx serve books
    environment: *node-variables
    ports:
      - 3004:3000
      - 9233:9229
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: superSecretPassword
    ports:
      - 6379:6379

  db:
    image: postgres:14-alpine
    volumes:
      - ./dev-db:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  pg-data:
