version: '3.8'

x-node-variables: &node-variables
  NODE_ENV: development

services:
  books:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ./node_modules/.bin/nx serve books
    environment: *node-variables
    ports:
      - 3001:3000
      - 9230:9229
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: superSecretPassword
    ports:
      - 6379:6379

  db:
    image: postgres:14-alpine
    volumes:
      - ./database-initialization:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@rental.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5000:80
    logging:
      driver: none

volumes:
  pgadmin-data:
