name: Node.js CI

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ hashFiles('**/package-lock.json') }}
      - run: npm ci

  e2e-tests:
    runs-on: ubuntu-18.04
    steps:
      # - run: npm run test:e2e
      - run: echo ok
    needs: install-dependencies
