name: Node.js CI

on: [push]

jobs:
  install-dependencies:
    - uses: actions/checkout@v2
    - run: npm i

  unit-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        apps: [books, database-storage]
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: nx test ${{ matrix.apps }}
    needs: install-dependencies

  e2e-tests:
    runs-on: ubuntu-18.04
    steps:
      # - run: npm run test:e2e
      - run: echo ok
    needs: install-dependencies
